name: Machinekit
highlighter: rouge
relative_permalinks: false
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
repository: https://github.com/machinekit/machinekit

gems:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - jekyll-sitemap

url: http://preview.machinekit.io

asciidoc: asciidoctor
asciidoc_ext: asciidoc,ad

asciidoctor:
  safe: 0
  attributes:
    - hardbreaks!

#incremental: yes

defaults:
  -
    scope:
      path: ""
    values:
      edit-repo: "https://github.com/machinekit/machinekit-docs/"
      edit-branch: "master"
  -
    scope:
# applies to all files under:
      path: "docs"
    values:
      layout: "docs"
      docs-dir: "docs"


# stage manpage sources here for comparison
exclude: [Makefile,
	 staging,
	 scripts,
	 src,
	 README.md,
	 '*/*.1',
	 '*/*.1.in',
	 '*/*.3hal',
	 '*/*.3rtapi',
	 '*/*.9' ]

# Google services - preview.machinekit.io
google_analytics:   UA-48383649-2

# for www.machinekit.io - activate on switch!
#google_analytics:  UA-48383649-1
