name: Machinekit
highlighter: rouge
relative_permalinks: false
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
repository: https://github.com/machinekit/machinekit

gems:
  - jekyll-asciidoc
  - asciidoctor-diagram

asciidoc: asciidoctor
asciidoc_ext: adoc,ad

asciidoctor:
  safe: 0
  attributes:
    - hardbreaks!
